"""Add unique constraint to pantry items

Revision ID: 46ec0ab64dc0
Revises: 6a6420cfa7a3
Create Date: 2025-11-10 16:38:35.879034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46ec0ab64dc0'
down_revision: Union[str, Sequence[str], None] = '6a6420cfa7a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_ingredient', 'pantry_items', ['user_id', 'ingredient_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_ingredient', 'pantry_items', type_='unique')
    # ### end Alembic commands ###
