"""Add unique constraint on user_recipe_interactions

Revision ID: 6a6420cfa7a3
Revises: 098bcc470c22
Create Date: 2025-11-08 21:26:19.692644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a6420cfa7a3'
down_revision: Union[str, Sequence[str], None] = '098bcc470c22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_recipe', 'user_recipe_interactions', ['user_id', 'recipe_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_recipe', 'user_recipe_interactions', type_='unique')
    # ### end Alembic commands ###
